### ISSUE TITLE
Ags with busname "ags" is already running

### ISSUE THREAD

**Issue by cakarmustactalone** [Aylur/ags#172]
I have installed "aylurs-gtk-shell" from aur, and copied ags configuration of @Aylur , but I got this error, and nothing changed on the screen . Before that I had gnome-Bluetooth issue ,luckily anyone opened issue and it is solved. But this is unfamiliar and I am foreigner  to this Java script environment? Any help? Thx

Edited: 
Now it gives me Failed to execute child process "ydotoold"  no such file or direcory. 

I think it comes  as an aur dependency

**Comment by Aylur** [comment]
If you don't specify a name with `--bus-name` it defaults to `ags`. Now with that, `Ags with busname "ags" is already running` means exactly what it says, stop it by running `ags --quit`
if its already running and you don't see anything happen, it must be because there was an issue in the config and it couldn't start.
Start it in a terminal, read the logs and start troubleshooting from there.
My configuration doesn't depend on `ydotoold` though

**Comment by Aylur** [comment]
Do you have `sassc` installed?

**Comment by cakarmustactalone** [comment]
Thanks @Aylur you are awesome, sorry I thought that AUR will handle that but my bad. You can close it now
