### ISSUE TITLE
Upstream to nixpkgs?

### ISSUE THREAD

**Issue by SystematicError** [Aylur/ags#251]
Are there any plans to upstream the package to nixpkgs? It would be a nicer experience for an end user to download AGS via the official nixpkgs repositories as flakes wouldn't be a hard requirement and a binary cache would be available.

Is this just something that has not been considered yet? Or are there no willing upstream maintainers?

**Comment by Aylur** [comment]
I didn't want to upstream it because I wasn't happy with the project yet, and there were a lot of breaking changes. But its matured a lot since and I plan on marking it as stable soon.
I haven't looked into how to contribute to nixpkgs yet as I am still new to nix, and even if it got accepted I would still use the flake instead, but if anyone decides to make a PR for it that would be cool.

**Comment by SystematicError** [comment]
Well the derivation file has already been written so that's the hard part done, most of the future maintenance would probably just involve updating dependencies or hashes. Nixpkgs has a [guide](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md) for package maintainers in case you're interested.
