### ISSUE TITLE
network.wired.speed not working

### ISSUE THREAD

**Issue by phonetic112** [Aylur/ags#286]
`network.wired.speed` just returns `1000` and nothing useful.

**Comment by milesdm** [comment]
That's just reporting the connected speed of the ethernet connection (essentially /sys/class/net/$device/speed). 
I wouldn't say that's not useful. What were you looking for? 

The network service needs some work according to Aylur in the docs.   I might actually give it a shot when I have some time, because I'd personally like to see MAC Addresses, arrays of IPv4 and IPv6 address, things of that nature that Network Manager should be able to return.

**Comment by phonetic112** [comment]
oh I was just looking for the current download speed/usage. I ended up writing my own implementation using ifstat so it's fine. thanks

**Comment by chikobara** [comment]
> oh I was just looking for the current download speed/usage. I ended up writing my own implementation using ifstat so it's fine. thanks

cool, can you share it ?
