### ISSUE TITLE
how to update ags without cloning the repo again

### ISSUE THREAD

**Issue by fr13ndxd** [Aylur/ags#3]
how do i update ags without cloning the repo again

**Comment by gnmearacaun** [comment]
I guess you could fork the repo, add upstream, `git fetch` and `git merge upstream`

**Comment by Incognitux** [comment]
just `git pull` should work no?

**Comment by jointdev** [comment]
Would be nice an AUR package

**Comment by kotontrion** [comment]
There are AUR packages. They're called `aylurs-gtk-shell` and `aylurs-gtk-shell-git`. 

The git version won't update automatically, you have to rebuild it regularly by using e.g. --devel option of yay. I would still recommend the git package if you've already updated your config, because there were a lot of changes since the last release. You could then switch to the non git version once version 1.0.0 is released.

If you've followed the install instructions listed in the wiki, ags will be installed under the `/usr/local` prefix, but the AUR packages follow the Arch guidelines and install to `/usr` instead, so you would have to manually uninstall your current non-AUR install. Otherwise ags would be installed twice on your system on different paths. You can see a list of installed files in the `install-log.txt` in the build directory.

**Comment by fr13ndxd** [comment]
![image](https://github.com/Aylur/ags/assets/127687150/4331b332-13d7-4c92-b580-b37b88029fb0)
its javascript not javascrip

**Comment by fr13ndxd** [comment]
![image](https://github.com/Aylur/ags/assets/127687150/c8bcb8af-78b1-43e9-b9e4-e6556202e3c2)
Also you could say "Typescript & javascript" instead of "javascript"

**Comment by kotontrion** [comment]
It does say javascript in the description, I just looked it up. For some reason it's cut of. But now that i think about it, maybe it shouldn't be mentioned at all.
I will probably change it to `aylur's gtk shell (ags), an eww inspired gtk widget system` later then.

**Comment by fr13ndxd** [comment]
make some letters capital too, ```Aylurs's Gtk Shell (AGS), An eww inspired gtk widget system.```

**Comment by fr13ndxd** [comment]
![image](https://github.com/Aylur/ags/assets/127687150/f177f220-2df3-4a10-bfc7-dcbd5d65592a)
also somehow the votes updated like 10-15 minutes after i gave the votes

**Comment by Aylur** [comment]
the flake and aur package should suffice, so closing this
also added the aur package to the wiki
