### ISSUE TITLE
Neovim?

### ISSUE THREAD

**Issue by rafaeljacov** [Aylur/ags#369]
![image](https://github.com/Aylur/ags/assets/110229646/f4391049-faca-4891-a7f1-c2e46dbdd018)

I have run "ags --init" but LSP still doesn't know it
I'm using tsserver for my LSP

**Comment by h-banii** [comment]
hmm from the screenshot it seems that the `types` symlink is missing. It should've been created automatically by the command `ags --init`, but apparently it didn't...

I just tested it on Arch, ags v1.8.0 (AUR), and tsserver LSP on neovim seems to be working.
![image](https://github.com/Aylur/ags/assets/121690516/96754309-d949-4cbe-be2f-b2788dd304a4)

So the problem is likely on `ags --init` not creating the symlink correctly in your case.

OBS.: If you open that README file it'll tell you where the symlink was supposed to point to, it might be different if you're using nix
![image](https://github.com/Aylur/ags/assets/121690516/85f509a7-5753-440c-9282-31af6b4354b5)

**Comment by rafaeljacov** [comment]
> hmm from the screenshot it seems that the `types` symlink is missing. It should've been created automatically by the command `ags --init`, but apparently it didn't...
> 
> I just tested it on Arch, ags v1.8.0 (AUR), and tsserver LSP on neovim seems to be working. ![image](https://private-user-images.githubusercontent.com/121690516/318134936-96754309-d949-4cbe-be2f-b2788dd304a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3NTgzMjgsIm5iZiI6MTcxMTc1ODAyOCwicGF0aCI6Ii8xMjE2OTA1MTYvMzE4MTM0OTM2LTk2NzU0MzA5LWQ5NDktNGNiZS1iZTJmLWIyNzg4ZGQzMDRhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMFQwMDIwMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYTYzNzEwMmE2YzcxOTE4ZmUxNWQ4NmQ0NDVkNjgwNTUyMDZhNGE1YzMxNjE1ZDM5MzgxMjk4NzYxMzZmZjUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cSbvqm4rGXtXC0z2HkhkWSQi4p98XzlIUtqIjRF086c)
> 
> So the problem is likely on `ags --init` not creating the symlink correctly in your case, not neovim.
> 
> OBS.: If you open that README file it'll tell you where the symlink was supposed to point to, it might be different if you're using nix ![image](https://private-user-images.githubusercontent.com/121690516/318133086-85f509a7-5753-440c-9282-31af6b4354b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3NTgzMjgsIm5iZiI6MTcxMTc1ODAyOCwicGF0aCI6Ii8xMjE2OTA1MTYvMzE4MTMzMDg2LTg1ZjUwOWE3LTU3NTMtNDQwYy05MjgyLTMxYWY2YjQzNTRiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMzMFQwMDIwMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NTczY2ViMjg2ZDQ1ODkwZDA3NThiYmYzYTljNjVmNTcyMDMwZmQyMDJjNWM5ODRiY2Y1NjA2ZTM5YmJiNzViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PMYkYfUlBAQ3BaW4C-x1oeKT7RYHNDCGRFUi2mpqGUE)

Strange, I ran ls command and it shows in the shell that the symlink does exist, but doesn't show on NvimTree
![image](https://github.com/Aylur/ags/assets/110229646/d3522ea3-4c3e-4f40-89d6-1c89fe3fdd31)

**Comment by h-banii** [comment]
@rafaeljacov 

Ah I see, try turning on the "build_types" option when building with meson, like this:

```sh
meson setup build --wipe -Dbuild_types=true
meson install -C build
```

I just tested it on fedora and it should probably work for you as well (hopefully).

Alternatively, you can set the build_types option in the meson_options.txt file (it's set to false by default).

**Comment by rafaeljacov** [comment]
> @rafaeljacov
> 
> Ah I see, try turning on the "build_types" option when building with meson, like this:
> 
> ```shell
> meson setup build --wipe -Dbuild_types=true
> meson install -C build
> ```
> 
> I just tested it on fedora and it should probably work for you as well (hopefully).
> 
> Alternatively, you can set the build_types option in the meson_options.txt file (it's set to false by default).
> 
> EDIT: I'm almost certain meson already runs the post_install.sh script, so you probably don't need to do that.

I get this at the end of compilation even it the tsc command is available on my shell:
Running custom install script '/usr/bin/env bash /home/rafaeljacov/ags/post_install.sh /usr/local/share /usr/local/share/com.github.Aylur.ags /usr/local/bin com.github.Aylur.ags true /home/rafaeljacov/ags'
/home/rafaeljacov/ags/post_install.sh: line 23: tsc: command not found

**Comment by h-banii** [comment]
Usually nvm requires updating the PATH through .profile or .bashrc, so I guess meson doesn't source those files when running the installation.

There are a few different ways to fix that error in your specific case:
- Change line 23 in the script to use the full path to tsc instead of just tsc
- Source .profile or .bashrc (or whatever file you use) inside the post_install script
- Run the script manually in your shell (with the same arguments that meson outputted)

Or this fix that should work anywhere:
- [h-banii/ags/tree/fix/post_install](https://github.com/h-banii/ags/tree/fix/post_install) (this uses local tsc instead of the global one to compile the `types` folder)

Not sure if I should open a PR for that branch, I believe it's a neat solution, but for the time being I'll just link it here just in case there are other people with global npm installations or custom installations of tsc.

**Comment by rafaeljacov** [comment]
Yes I also thought it would just be better to use the local tsc instead. I just fixed my problem by referencing the full path to my tsc. Thanks

**Comment by rydymth** [comment]
> Alternatively, you can set the build_types option in the meson_options.txt file (it's set to false by default).


Thnkyou @h-banii! 
Editing the meson-options.txt worked for me!
