### ISSUE TITLE
Gtk-Warning Theme Parsing Error

### ISSUE THREAD

**Issue by nuerocist** [Aylur/ags#430]
When I try to run the command `ags` it returns with

``(com.github.Aylur.ags:17182): Gtk-WARNING **: 17:25:18.142: Theme parsing error: gtk.css:3213:16: Unit is missing.``

``(com.github.Aylur.ags:17182): Gjs-Console-CRITICAL **: 17:25:18.241: Gio.IOErrorEnum: Could not connect: No such file or directory
socket@resource:///com/github/Aylur/ags/service/hyprland.js:7:6
Hyprland@resource:///com/github/Aylur/ags/service/hyprland.js:108:26
@resource:///com/github/Aylur/ags/service/hyprland.js:278:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34``

I'm new to ags and I don't really know what to do.

**Comment by kotontrion** [comment]
> (com.github.Aylur.ags:17182): Gtk-WARNING **: 17:25:18.142: Theme parsing error: gtk.css:3213:16: Unit is missing.

This is an issue with you gtk theme because it probable uses something like `padding: 5`; instead of `padding: 5px`. You can usually ignore this. Gtk just assumes the unit is in px and warns you about it, as this assumption might be wrong. This would have to be fixed in your gtk theme. 

> (com.github.Aylur.ags:17182): Gjs-Console-CRITICAL **: 17:25:18.241: Gio.IOErrorEnum: Could not connect: No such file or directory socket@resource:///com/github/Aylur/ags/service/hyprland.js:7:6 Hyprland@resource:///com/github/Aylur/ags/service/hyprland.js:108:26 @resource:///com/github/Aylur/ags/service/hyprland.js:278:25 _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

This is the actual error here.
ags can't find the Hyprland socket.
There are two possible reasons for this:
1. You don't use Hyprland as you compositor, then you can't use the hyprland service.
2. You are running an old version of ags.

Hyprland moved it's socket in version v0.40.0, this leads to the error described here. This is fixed ags version 1.8.2, so make sure you are up to date.

**Comment by nuerocist** [comment]
Thanks! Using 1.8.2 has seemed to have fixed the issue. But now there is another warning which says

`(com.github.Aylur.ags:48537):` Gjs-Console-CRITICAL **: 22:32:58.559: ReferenceError: App is not defined
@file:///home/nuero/.config/ags/config.js:4:18
`_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34`
  
Any idea on how to fix this?

**Comment by kotontrion** [comment]
This error is a weird one.
App should always be defined and it is a global variable, so you don't even have to import it.
The only way I can think of how this error could appear is as a sideeffect of other errors.
So, are there any other errors in the output? If so, please provide the whole log.

**Comment by nuerocist** [comment]
I managed to fix it by installing ags from source. Everything seems to work now! Thank you for your help.
