### ISSUE TITLE
Nothing display in the second monitor

### ISSUE THREAD

**Issue by trlsmax** [Aylur/ags#551]
How to config ags to support multi monitors.
But hyprland managed app can display well.

**Comment by kotontrion** [comment]
A window can't be displayed at multiple monitors at once. You have to handle multiple monitors yourself. The best way is to use either hyprland service  or gdk to get the monitors to create a window for each one. Also connect to the  monitor-added/removed signals to remove and create windows when monitors are connected and disconnected while ags is running.

In my config I use gdk for that, because I don't use hyprland.

https://github.com/kotontrion/dotfiles/blob/main/.config%2Fags%2Fconfig.js#L60-L74

**Comment by trlsmax** [comment]
> A window can't be displayed at multiple monitors at once. You have to handle multiple monitors yourself. The best way is to use either hyprland service or gdk to get the monitors to create a window for each one. Also connect to the monitor-added/removed signals to remove and create windows when monitors are connected and disconnected while ags is running.
> 
> In my config I use gdk for that, because I don't use hyprland.
> 
> https://github.com/kotontrion/dotfiles/blob/main/.config%2Fags%2Fconfig.js#L60-L74

Oh, thank you. I will try this.
