### ISSUE TITLE
Problem with binding variables

### ISSUE THREAD

**Issue by NekoChanFan** [Aylur/ags#553]
I'm new to AGS and JS. Today I tried some of examples from wiki and got stuck with a problem. 
In Reactivity section there is an example:
```js const label = Variable("hello")

let myLabel = Widget.Label({
    // [Object object] world
    label: `${label.bind()} world`,

    // hello world
    label: label.bind().as(hello => `${hello} world`)
})
```
window and App.config, but there's nothing unusual, I guess:
```js 
const win = Widget.Window({
  name: "name",
  anchor: ["top", "right"],
  child: myLabel,
})

App.config({
  windows: [win],
})
````
If I comment out second variant, I get the same result, as in wiki(widget, displaying "[object Object] world"), but if I leave only the right way to do binding and comment out first variant, I get nothing displayed. 

This label is empty:
```js
let myLabel = Widget.Label({
    label: label.bind().as(hello => `${hello} world`)
})
```
What am I doing wrong and what is the right way to use and bind variables?

**Comment by kotontrion** [comment]
the issue is not the bind, but the window. When using a bind, the label is initially empty and the get updated later. The window has only one child, the empty label. Therefore it has initially no size, which leads to the window not showing up, this is [common issue](https://aylur.github.io/ags-docs/config/common-issues/).

**Comment by NekoChanFan** [comment]
Thanks a lot!!!
