### ISSUE TITLE
Mpris album cover

### ISSUE THREAD

**Issue by filippoaceto22** [Aylur/ags#559]
Hi, i use strawberry With qobuz. I add a media panel in AGS and  the image of the album is empty. I use the bind With  cover_path.
In the debug i see that strawberry not save the image in the cache .cache/ags. Spotify works.

Its a problem related ti strawberry?

**Comment by yashranjan1** [comment]
Mpris does not completely support every player, [docs page](https://aylur.github.io/ags-docs/services/mpris/)

> Its a problem related ti strawberry?

I dont think the problem is related the player, but with mpris. A problem I face is with length and position on chrome. Instead of resetting the length and position when one song ends and the next begins, mpris just adds the length of the new song onto the length the old songs and then keeps the position going.

**Comment by filippoaceto22** [comment]
With strawberry from flatpack I had this problem. By downloading that from the arch Linux repositories it no longer occurs.
