### ISSUE TITLE
[Issue] How lazy load ags? Or make sure that the options in ags change without restarting

### ISSUE THREAD

**Issue by sh1zicus** [Aylur/ags#633]
my ags takes quite a long time to start, 5-7 seconds,
I have a gjs script that switches options in modules and after that ags should restart.
Is it possible to somehow load some modules lazily or change module options in ags without restarting it?

**Comment by Aylur** [comment]
> 5-7 seconds

sounds like you have some expensive blocking operation that should be reworked

> load some modules lazily

making use of the bundler you can do something like this

```js
// a.js
console.log("some very heavy operation")
export const value = "value";
```

```js
// b.js
async function getValue() {
  const { value } = await import("./a.js") // load the module async
}
```

but if you statically import it in any module, it will still be evaluated at startup though
```js
import { value } from "./a.js"
```

all this does is just wrap your module in a function, which might not be what you want
since you did not provide much context, my guess is you have some `exec("heavy-operation")` that takes too long, you should use `execAsync` instead.

If all you want to do is to change some values at runtime you can use the cli client
```js
// options.js
export const options = {
  opt: Variable("value")
}

// app.tsx
import { options } from "./options"

App.start({
  requestHandler(req, res) {
    const [cmd, opt, value] = req.split(" ")
    if (cmd == "set") {
      options[opt].set(value)
      return res("ok")
    }
    res("unknown command")
  }
  main() {
    return <window>
      <label label={options.opt()} />
    </window>
  }
})
```

```sh
astal set opt "new value"
```
