### ISSUE TITLE
notifications useMarkup crashes when markup is not ok

### ISSUE THREAD

**Issue by DevAlien** [Aylur/ags#84]
I received a message on slack with the following content (keys have been changed):

```
Sleekplan code ID 321345123

SSO Key 390293029302930290329032903290392
https://sleekplan.com/docs/single-sign-on/

Widget install docs
https://sleekplan.com/docs/install/widget.html#_3-optional-setup-a-custom-button
https://help.sleekplan.com/en/articles/5149611-install-the-sleekplan-widget

Here is the sleekplan code widget right before closing </body>

<script type="text/javascript">window.$sleek=[];window.SLEEK_PRODUCT_ID=321345123;(function(){d=document;s=d.createElement("script");s.src="https://client.sleekplan.com/sdk/e.js";s.async=1;d.getElementsByTagName("head")[0].appendChild(s);})();</script> 
```

I get failed to set text ....... from markup due to error parsing markup: Error on line 12 char 63: Element “body” was closed, but the currently open element is “markup”.

This makes it impossible to clear the notification causing ags to crash. Basically the error is replicated many many times and then I get
`Lost connection to Wayland compositor.`

An idea would be to just use simple markup and stuff like body/script etc we should replace the < and > with &#60; and &#62;?

I could work on this, if this seems like a possible solution.

**Comment by kotontrion** [comment]
Yes, this happens when the notifications contains tags which are not recognized by pango. I could replicate this as well.

> An idea would be to just use simple markup and stuff like body/script etc we should replace the < and > with < and >?

That would only be a partial solution. As the text could contain valid tags, but was not intended to be pango markup, like containing an \<b\> tag without closing it. This would result in the same error.

I guess the easier and more robust way to fix this would be using `Glib.markup_escape_text` if the pango parser fails.

**Comment by DevAlien** [comment]
In which case would be important to support html?

The clear not working for me it is different, even without markup it crashes.
